language: swift
osx_image: xcode8.3
branches:
  only:
    - master
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=TravisDemo.xcworkspace
  - IOS_FRAMEWORK_SCHEME="TravisDemo"
  - EXAMPLE_SCHEME="TravisDemo"
  matrix:
    - DESTINATION="OS=10.3,name=iPhone 7 Plus"     SCHEME="$IOS_FRAMEWORK_SCHEME"   RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="YES"
before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -workspace TravisDemo.xcworkspace -scheme TravisDemo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7 Plus,OS=10.3' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)